# Generated by Django 5.1.2 on 2024-10-12 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_name', models.CharField(max_length=20)),
                ('boat_service', models.CharField(default='1', max_length=50)),
                ('boat_deck', models.CharField(default='Single Deck', max_length=50)),
                ('boat_capacity', models.IntegerField()),
                ('boat_entrydate', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_eventtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('event_rate', models.IntegerField()),
                ('event_details', models.CharField(max_length=5000)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stationmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_gender', models.CharField(max_length=20)),
                ('master_contact', models.CharField(max_length=20)),
                ('master_address', models.TextField()),
                ('master_photo', models.FileField(upload_to='UserImages/')),
                ('master_proof', models.FileField(upload_to='UserImages/')),
                ('status', models.IntegerField(default=1)),
                ('master_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_place')),
                ('master_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
