# Generated by Django 5.1.2 on 2024-10-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_stationmaster',
            old_name='master_user',
            new_name='user',
        ),
    ]
